version: "2"

volumes:
  ui-modules:

services:
  ui:
    image: node:12-stretch
    hostname: ui
    tty: true
    environment: &environment
      TERM: "xterm-256color"
      NODE_ENV: "development"
    mem_limit: 512M
    volumes:
      - $PWD/ui:/srv/ui:delegated
      - $PWD/ocfl-repository:/srv/ui/dist/repository:delegated
      - ui-modules:/srv/ui/node_modules:delegated
    working_dir: /srv/ui
    command: ["npm", "run", "develop"]
    ports:
      - 9001:9001
