version: "2"

volumes:
    ui-modules:
    api-modules:
    search:

services:
    ui:
        image: nginx:latest
        hostname: ui
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "production"
        mem_limit: 1024M
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./ui/dist:/usr/share/nginx/html:delegated
            - ./nginx/configuration.json:/usr/share/nginx/html/configuration.json
            - ./ocfl-repository:/srv/repository:delegated
            - ui-modules:/srv/ui/node_modules:delegated
        ports:
            - 80:80

    search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        hostname: search
        environment:
            - node.name=search
            - discovery.seed_hosts=search
            - bootstrap.memory_lock=true
            - http.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
        working_dir: /usr/share/elasticsearch
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - search:/usr/share/elasticsearch/data:delegated
            - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elastic/roles.yml:/usr/share/elasticsearch/config/roles.yml
            - ./elastic/users:/usr/share/elasticsearch/config/users
            - ./elastic/users_roles:/usr/share/elasticsearch/config/users_roles
        ports:
            - 9200:2300
