version: "2"

volumes:
    ui-modules:
    api-modules:

services:
    ui:
        image: nginx:latest
        hostname: ui
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "production"
        mem_limit: 512M
        volumes:
            - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - $PWD/ui/dist:/usr/share/nginx/html:delegated
            - $PWD/nginx/configuration.json:/usr/share/nginx/html/configuration.json
            - $PWD/ocfl-repository:/usr/share/nginx/html/repository:delegated
            - ui-modules:/srv/ui/node_modules:delegated
        ports:
            - 80:80

    search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
        hostname: search
        environment:
            - node.name=search
            - discovery.seed_hosts=search
            - cluster.initial_master_nodes=search
            - cluster.name="search"
            - bootstrap.memory_lock=true
            - http.host=0.0.0.0
            - xpack.security.enabled=true
            - xpack.security.http.ssl.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        mem_limit: 1024m
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - $PWD/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - $PWD/elastic/roles.yml:/usr/share/elasticsearch/config/roles.yml
            - $PWD/elastic/users:/usr/share/elasticsearch/config/users
            - $PWD/elastic/users_roles:/usr/share/elasticsearch/config/users_roles
        ports:
            - 9200:9200
